# Generated by Django 5.1.7 on 2025-03-24 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline', 'priority']},
        ),
        migrations.AlterModelOptions(
            name='worker',
            options={'ordering': ['position', 'last_name']},
        ),
    ]
